# Generated by Django 3.1.2 on 2022-03-02 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_sub_category',
            name='category',
        ),
    ]
