# Generated by Django 4.0.3 on 2022-04-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0007_alter_order_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
