# Generated by Django 4.0.3 on 2022-04-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0008_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='num_stars',
            field=models.FloatField(default=0),
        ),
    ]
