# Generated by Django 4.0.3 on 2022-04-25 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0011_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
