# Generated by Django 4.0.3 on 2022-04-25 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0012_rename_product_name_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image1',
            new_name='image',
        ),
    ]
